### ISSUE TITLE
Mistake in instructions 

### ISSUE THREAD

**Issue by twosh** [dala318/nordpool_planner#16]
Hi,

Noticed that in the instructions this line is used a few times:

`var_duration_entity_id: sensor.needed_ammount_of_hors`

I think it should be

`var_duration_entity: input_number.needed_ammount_of_hours`

In the code you don't have the `_id` part, and I also guess that the entity type should be input_number and not sensor.

Cheers,
Tim

**Comment by dala318** [comment]
Documentation fixed, thanks for sharing your finding
