### ISSUE TITLE
Cant add sensor

### ISSUE THREAD

**Issue by flippz** [dala318/nordpool_planner#2]
Just get this error:

Configuration validation
Validate your configuration if you recently made some changes to it and want to make sure that it is all valid.
Configuration invalid!

Platform error sensor.nordpool_planner - No module named 'custom_components.nordpool_planner.sensor'

Iv added it via hacs

**Comment by dala318** [comment]
Sorry for that, forgot to update documentation. Shall be under "binary_sensor".
Will fix dokumentation asap

**Comment by dala318** [comment]
The documentation is updated in release 0.1.2 but you don't have to update, just change the setting in your configuration.yaml
Version 0.1.2 also has new a feature which I haven't had time to test that much so safe option is to stay on v0.1.1 and just update config, but are happy to receive feedback on new feature if you want to test it

**Comment by flippz** [comment]
I would like to test yes :) Ill do an upgrade.
BTW on 0.1.1 i get this error:
Invalid config for [binary_sensor.nordpool_planner]: [accept_level] is an invalid option for [binary_sensor.nordpool_planner]. Check: binary_sensor.nordpool_planner->accept_level. (See ?, line ?).
