### ISSUE TITLE
Explain values

### ISSUE THREAD

**Issue by flippz** [dala318/nordpool_planner#5]
Hi. Could you please explain the expressions below a bit better?

duration: What do u mean?

accept_cost: are we talking a actual price here?

accept_rate what are the numbers here?

now_cost_rate what is this value?

**Comment by dala318** [comment]
I'll see of I find time to clarify in readme.md.

"duration" is the number of consecutive hours you need energy, i.e. the size of the time window sliding over the "search_length" to find the lowest average.

"accept_cost" is a price that gets accepted if found. No more searching is done.

"accept_rate" similar but a tate comparing the to Nordpool reported average price. If set to 1 an average over duration <= nortpool is accepted. If 0.5 it has to be half the price of nordpool average.

"now_cost_rate" is just a comparison to how much more expensive the electricity right now is compared to the found slot. 2 means you could half the cost by waiting for the found slot.
