### ISSUE TITLE
Do some proper work in the STATIC planner variant

### ISSUE THREAD

**Issue by dala318** [dala318/nordpool_planner#54]
The selection of STATIC planner is enabled but there is almost no logic connected to it. Implement and test it...

- [x] Fix the basics (just get a proper end-time from exact time instead of offset from now) [DONE in #55 ]
- [x] How to keep track of "used" hours for every cycle (need some persistent memory so that it don't reset if HA is restarted). 
- [x] Make some use of the "used_hours" data to stop if fulfilled (off if used_hours >= duration)
- [x] Add service/button to reset the used hour within an active span (could sort of solve the "car not connected" issue, reset by external automation when car is connected)
- [x] ~~Enable option to split the hours over the entire day (the cheapest hours don't have to be consecutive). In reality the duration becomes "find the X cheapest hours" and the duration in logic is set to 1~~ Split out to separate issue #71 
- [x] Set a start-hour (specially for a car charger the vehicle is likely not connected during the day when used and then the integration should not be enabled)
- [x] ~~Postpone start-hour if external condition not fulfilled (ex. car not connected). Will likely be split to separate task, and could be that it not even fits to this integration.~~ Won't do!
- [ ] Test it for release!

**Comment by dala318** [comment]
> How is the progress of the work with "STATIC planner"? Do you want to implement control by power levels (kWh average over an hour), and add prioritized loads/units in the future?
> 
> Can you look into the possibility of a sensor that sets the water temperature in the hot water tank, depending on the electricity price?

Hi, progress is slow on this particular part of the planner (most likely because I don't have an immediate use of it myself), but should maybe start a poll or something to see how large the interest of it is.

About your proposals above, improvements and suggestions are always welcomed. Could you explain a bit more what you're after. Maybe as one or two separate tickets. (this particular ticket only aims to finalize the core functionality of the static planner)

**Comment by ojm88** [comment]
Hi, and thanks for your reply.

See my new "issue" I have started. Answering your questions there.

> > How is the progress of the work with "STATIC planner"? Do you want to implement control by power levels (kWh average over an hour), and add prioritized loads/units in the future?
> > Can you look into the possibility of a sensor that sets the water temperature in the hot water tank, depending on the electricity price?
> 
> Hi, progress is slow on this particular part of the planner (most likely because I don't have an immediate use of it myself), but should maybe start a poll or something to see how large the interest of it is.
> 
> About your proposals above, improvements and suggestions are always welcomed. Could you explain a bit more what you're after. Maybe as one or two separate tickets. (this particular ticket only aims to finalize the core functionality of the static planner)

Hi, and thanks for your reply.

See my new "issue" I have started. Answering your questions there.
