### ISSUE TITLE
ENTSO-e sensor not pickable

### ISSUE THREAD

**Issue by jarno83** [dala318/nordpool_planner#58]
Hi.
Installed addons: Entso-e, Nordpool, Nordpool-diff,
Problem: No entso-e sensors to pick when installed the planner. Both nordpools where in the list.

Thank you :)

**Comment by dala318** [comment]
What's the entity name of your entso-e average price sensor entity?
I've might have set the filter a bit strict but need to know how entity names may differ to be able to adapt.
Yet I have not figured out how to get entities filtered by integration so have to make assumptions based on entity names.

**Comment by jarno83** [comment]
Thank you for your reply. I'll add a picture of all entities what entso-e has made. I hope it helps, if you need anything else let me know. Thanks again :)
![entso-e entities](https://github.com/user-attachments/assets/0c9fb57d-6aba-42aa-b4cd-09287e977f8f)

**Comment by dala318** [comment]
Thanks, I was not that far off but apparently I need to remove the "_today" from the filter [here](https://github.com/dala318/nordpool_planner/blob/main/custom_components/nordpool_planner/config_flow.py#L91).

```python
        selected_entities = [
            s
            for s in sensor_entities
            if "nordpool" in s or "average_electricity_price_today" in s
        ]
```

While I have time to fix and release a new version you can make the change yourself in `config/custom_components/nordpool_planner/config_flow.py`

**Comment by dala318** [comment]
But also, be aware that ENTSO-e planner is not really working as expected yet #57 (https://github.com/dala318/nordpool_planner/discussions/45#discussioncomment-10791297)
