### ISSUE TITLE
Duration almost never works for me

### ISSUE THREAD

**Issue by Dutchy-79** [dala318/nordpool_planner#59]
Hi,

First, I think it's a great job you have done so far.

Though I do have a question, for me the duration almost never works.

For example, today there will be several hours of low prices. I've set it to 4 hours and it still says 12:00+2

When changing it to 3 hours it still says +2 every time it changes.

I'm trying to heat up the heat pump boiler so it does take some time to heat up the water.

Did I setup something wrong?

![Screenshot_20241020_064439_Zonneplan](https://github.com/user-attachments/assets/03a4c18a-863f-44f2-bc65-c05ab2e5f39d)
![Screenshot_20241020_064510_Home Assistant](https://github.com/user-attachments/assets/ecbe9788-a671-4b65-97bd-c25dae0791e0)

**Comment by dala318** [comment]
The +2 in your "Low cost start at" sensor would be your time-zone (how your Home Assistant chose to display a "time of the day")

**Comment by Dutchy-79** [comment]
Ty, completely misunderstood.

I thought it was 12:00 "On" for 2 hours.
