### ISSUE TITLE
Implementation of Priceanalyzer's possibilities in Nordpol_planer

### ISSUE THREAD

**Issue by ojm88** [dala318/nordpool_planner#67]
Hello again.

What I'm looking for in nordpool_planner are the same possibilities as erlendsellie
/
priceanalyzer
https://github.com/erlendsellie/priceanalyzer

This addition in Hacs no longer works after Nordpol changed its API. Erlend Sellie is very open to sharing his ideas and the solution with others, who have the opportunity to integrate the controls of PriceAnalyzer. Erlend does not have the time or opportunity to update the code after the API change in Nordpol.  

I would really appreciate it if you could contact Erlend and ask if you could cooperate. 

Your nordpool_planner and the possibilities previously contained in PriceAnalyzer will be completely invincible together. 

There is already a PriceAnalyzer_2 where Erlend describes the possibilities. 

https://github.com/erlendsellie/priceanalyzerv2/

Looking forward to further dialogue.

Regards, Ole J

**Comment by dala318** [comment]
I think that is almost achievable with current implementation by using a dynamic planner (search-length ~= 4 and duration = 1)
What you won't get by current implementation is a preview of when the second next cheap or expensive time is. But try it during some days and plot the history of Nordpool price and the binary states of Nordpool Planner and see what you get.

As i see the graph in [priceanalyzer](https://github.com/erlendsellie/priceanalyzer/tree/master) the greens are when the price is at the lowest in a limited future, reds almost the opposite but seem to be some hysteresis to is as there are some short dips where it keeps red. 

Of-course, if you want to step up or down your thermostats you need to add an automation on top of nordpool_planner (which only outputs the price state). I'm not so fond of adding actions on price state in this integration as it would make it less generic.

**Comment by ojm88** [comment]
> Jeg tror det er nesten oppnåelig med gjeldende implementering ved å bruke en dynamisk planlegger (søkelengde ~= 4 og varighet = 1) Det du ikke får ved nåværende implementering er en forhåndsvisning av når den nest neste billige eller dyre tiden er. Men prøv det i løpet av noen dager og plott historien til Nordpool pris og de binære statene til Nordpool Planner og se hva du får.
> 
> Som jeg ser grafen i [priceanalyzer,](https://github.com/erlendsellie/priceanalyzer/tree/master) er greenene når prisen er på det laveste i en begrenset fremtid, røde nesten motsatt, men ser ut til å være en viss hysterese fordi det er noen korte fall der den holder rødt.
> 
> Selvfølgelig, hvis du vil trappe opp eller ned termostatene dine, må du legge til en automatisering på toppen av nordpool_planner (som bare gir ut pristilstanden). Jeg er ikke så glad i å legge til handlinger på pristilstand i denne integrasjonen, da det ville gjøre den mindre generisk.

Hi.

Thanks for your answer.

You want me to store the information from your binary sensors and then create my own helpers that control the water temperature?
Sorry for asking "stupid" questions, but I'm not a computer programmer, and have only worked with HA for a year :)

Could you create an example of water temperature control using your binary sensors?

I understand that you may not want to implement the sensors for PA directly into NDP, but what about assisting Erlend Sellie to get PA2 up and running again after changes in the API to Nordpol? From what I experience of your knowledge, you are the right person for such tasks. I know there are many who will sponsor with "coffee" if PA gets up and running again. HA has become so common now, that it is important to have simple implementations that do not involve NodeRed.

Hoping for positive feedback again :-)

Best regards Ole Jørgen

**Comment by dala318** [comment]
I'll se what I can do, a free coffee always tast better 😋

**Comment by dala318** [comment]
For now I've added two blueprints that you cna try
https://github.com/dala318/nordpool_planner/blob/main/README.md#automation-blueprints

**Comment by dala318** [comment]
I'll close this one as the added blueprints should be as much as I can see fit into this integration
