### ISSUE TITLE
Plan electricity in a time-slot

### ISSUE THREAD

**Issue by dala318** [dala318/nordpool_planner#7]
For some usages a search time-span always moving ahead on now is not the best option, e.g. charging a car over night.
In that case it would more optimal to give an end-time and a total amount of hours needed, maybe also a boolean if the hours given must be consecutive or can be split in sections.
One thing to consider that may interfere with current logic is that the fact that it currently has no persistent state data, meaning several hours ahead of end-time the best hours could be selected, but as moving closer to that time there is less to choose from and if it's not remembering how many hours already used it will eventually end up choosing all remaining.

**Comment by flippz** [comment]
Could it not do the calculations of lowes price at time 00:00 and then find it within the next 24H and stick to what hours it finds?
